import os

total_lines = 0

file_counts = {}

for x,y,z in os.walk('.'):
    for file in z:
        if "faust" in file.lower(): # autogenerated files
            continue
        if file.endswith('.cpp') or file.endswith('.h'):
            with open(os.path.join(x, file), 'r') as f:
                lines = f.readlines()
                total_lines += len(lines)
                file_counts[file] = len(lines)

sorted_files = list(file_counts.keys())
sorted_files.sort(key= lambda x: file_counts[x])
sorted_files.reverse()

for file in sorted_files:
    print(f"{file}: {file_counts[file]}")
print(f"Total lines of code: {total_lines}")